import { useEffect, useState } from "react";
import { AppShell } from "../layouts/AppShell";
import { listSupervisorPlans, submitReview } from "../services/review-service";
import type { StudyPlan } from "../types/plans";

export function SupervisorPlansPage() {
  const [plans, setPlans] = useState<StudyPlan[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [feedback, setFeedback] = useState<Record<number, string>>({});
  useEffect(() => { void listSupervisorPlans().then(setPlans).catch(() => setError("Unable to load assigned study plans.")).finally(() => setLoading(false)); }, []);
  async function review(plan: StudyPlan, decision: "approved" | "revision_required") { try { await submitReview(plan.id, feedback[plan.id] ?? "", decision); setPlans((current) => current.map((item) => item.id === plan.id ? { ...item, status: decision } : item)); setError(null); } catch { setError("Feedback is required and the review could not be submitted."); } }
  return <AppShell><div className="space-y-6"><header><p className="text-sm font-medium text-primary">Supervisor workspace</p><h1 className="mt-2 text-3xl font-semibold">Assigned study plans</h1></header>{error && <p role="alert" className="text-destructive">{error}</p>}{loading ? <p role="status">Loading assigned study plans…</p> : plans.length === 0 ? <p>No assigned study plans.</p> : plans.map((plan) => <article key={plan.id} className="rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">{plan.summary}</h2><p className="mt-2">Status: {plan.status.replace("_", " ")}</p><p className="mt-2">Progress: {plan.progress}%</p><ol className="mt-4 space-y-2">{plan.tasks.map((task) => <li key={task.id}>Week {task.week}: {task.title} {task.is_completed ? "(completed)" : ""}</li>)}</ol>{plan.status === "generated" && <><label className="mt-4 block text-sm font-semibold" htmlFor={`feedback-${plan.id}`}>Feedback</label><textarea id={`feedback-${plan.id}`} className="mt-1 w-full rounded border p-2" value={feedback[plan.id] ?? ""} onChange={(e) => setFeedback({ ...feedback, [plan.id]: e.target.value })}/><div className="mt-3 flex gap-3"><button className="rounded bg-primary px-3 py-2 text-primary-foreground" onClick={() => void review(plan, "approved")}>Approve plan</button><button className="rounded border px-3 py-2" onClick={() => void review(plan, "revision_required")}>Request revision</button></div></>}</article>)}</div></AppShell>;
}
