# Generated by Django 5.2.17 on 2026-08-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('generated', 'Generated')], default='generated', max_length=32)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to='goals.academicgoal')),
            ],
            options={
                'ordering': ('-generated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AIExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('orchestrator', 'Agent Orchestrator'), ('planner', 'Planner Agent'), ('content_generator', 'Content Generator Agent'), ('evaluation', 'Evaluation Agent'), ('aggregator', 'Plan Aggregator')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('system_response', models.TextField(blank=True)),
                ('token_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='planning.studyplan')),
            ],
            options={
                'ordering': ('timestamp', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('method', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.studyplan')),
            ],
            options={
                'ordering': ('week', 'id'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'week', 'title'), name='unique_plan_week_task_title')],
            },
        ),
    ]
